name: Validate Homey App
on:
  workflow_dispatch:

jobs:  
    main:
      name: Validate Homey App
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: athombv/github-action-homey-app-validate@master
          with:
            level: verified